services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: villa-petriolo-backend-test1
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/villa-petriolo
      - REDIS_URL=redis://redis:6379
      - FRONTEND_URL=http://localhost:3000
      - MISTRAL_API_KEY=2ru1mNQglqLYfde6bnRXEMVt6EX9NEmL
      - OPENAI_API_KEY=your-openai-api-key-here
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    image: nginx:alpine
    container_name: villa-petriolo-frontend-test1
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  mongodb:
    image: mongo:6.0
    container_name: villa-petriolo-mongodb-test1
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: villa-petriolo-redis-test1
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data: